name: GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version 1.1.12
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          rm install-poetry.py
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.2"
          cache: 'poetry'
      - run: poetry install --no-dev
      - run: python -V
      - run: poetry run python -V
      - run: poetry run ./AQScripts.py
      - run: poetry run ./HistoricalGraph.py
      - name: Setup markdown-styles
        run: npm install -g markdown-styles
      - name: Generate website
        run:  generate-md --layout layout
      - name: Publish website
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
